version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      #- /data/postgres:/data/postgres
      - /var/lib/postgres/data:/usr/local/share/postgres/data
      #  - local_pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
 
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /var/lib/pgadmin/data:/usr/local/share/.pgadmin
      # - pgadmin-data:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
 
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    env_file:
      - docker.env 
    networks:
      - elastic
       
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge