# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Package
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Checkout Repository
      
      - name: Install Packages and Build 
        run: |
          npm install
          npm run build
      
      - uses: actions/upload-artifact@master
      - name: Upload Artifacts
        with: 
          name: build artifact
          path: dist/
   
  test:
    runs-on: ubuntu-latest 
    needs: build

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-2016]

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@master
      with: 
        name: build artifact
        path: dist
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Packages and Test
      run: |
        npm install
        npm test
      env:
        CI: true
