# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test - CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - uses: actions/upload-artifact@master
        with: 
          name: build artifact
          path: dist/
   
  test:
    runs-on: ubuntu-latest 
    needs: build

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-2016]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with: 
        name: build artifact
        path: dist
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, and test
      run: |
        yarn install
        yarn test
      env:
        CI: true
